if [[ 1 -eq 1 ]]; then
ARG=""; docker-compose ${ARG} --help > "${HOME}/man/docker-compose.help.man";
ARG="build"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="config"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="create"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="down"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="events"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="exec"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="help"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="images"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="kill"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="logs"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="pause"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="port"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="ps"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="pull"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="push"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="restart"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="rm"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="run"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="scale"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="start"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="stop"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="top"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="unpause"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="up"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
ARG="version"; docker-compose ${ARG} --help > "${HOME}/man/docker-compose-${ARG}.help.man";
fi;