<# ------------------------------------------------------------ #>

<#   Start-Process PowerShell.exe $(New-Object Net.WebClient).DownloadString("https://sync-ps.mcavallo.com/$((Date).Ticks).ps1") -Verb RunAs;   #>

<# ------------------------------------------------------------ #>

If (("AllSigned","Default","Restricted","Undefined") -contains (Get-ExecutionPolicy)) {
	Set-ExecutionPolicy "RemoteSigned" -Force;
}

Write-Host "Info:  Loading personal and system profiles...`n" -ForegroundColor Gray;

Write-Host "Info:  Local PowerShell Version: $(($($PSVersionTable.PSVersion.Major))+($($PSVersionTable.PSVersion.Minor)/10))`n" -ForegroundColor Gray;

<# ------------------------------------------------------------ #>

$AliasName="grep"; $AliasCommand="Select-String";
Write-Host "Info:  Checking for Alias `"${AliasName}`"..." -ForegroundColor Gray;
If ( (Get-Alias).Name -Contains "${AliasName}" ) {
	If ( ((Get-Alias -Name "${AliasName}").ResolvedCommand.Name) -Ne ("${AliasCommand}")) {
		Remove-Item "alias:\${AliasName}";
		New-Alias -Name "${AliasName}" -Value "${AliasCommand}";
	}
} Else {
	New-Alias -Name "${AliasName}" -Value "${AliasCommand}";
}

$AliasName="which"; $AliasCommand="Get-Command";
Write-Host "Info:  Checking for Alias `"${AliasName}`"..." -ForegroundColor Gray;
If ( (Get-Alias).Name -Contains "${AliasName}" ) {
	If ( ((Get-Alias -Name "${AliasName}").ResolvedCommand.Name) -Ne ("${AliasCommand}")) {
		Remove-Item "alias:\${AliasName}";
		New-Alias -Name "${AliasName}" -Value "${AliasCommand}";
	}
} Else {
	New-Alias -Name "${AliasName}" -Value "${AliasCommand}";
}

<# ------------------------------------------------------------ #>

Write-Host "Info:  Syncing local git repository to origin `"https://github.com/mcavallo-git/Coding.git`"..." -ForegroundColor Green;

If ( ${HOME} -Eq ${Null} ) {
	$HOME = ((Resolve-Path "~").Path);
}

$REPO_DIR_WIN32 = "${HOME}\Coding";

If (Test-Path "${REPO_DIR_WIN32}") {

	Set-Location "${REPO_DIR_WIN32}";

	git reset --hard "origin/master";

	git pull;

} Else {

	New-Item -ItemType ("Directory") -Path "${REPO_DIR_WIN32}" | Out-Null;

	# $SSH_KEY_REMOTE="https://raw.githubusercontent.com/mcavallo-git/Coding/master/.shared-deploy-key.pem";
	$SSH_KEY_LOCAL_WIN32="${HOME}\.ssh\id_rsa";
	# $SSH_KEY_LOCAL_WIN32="${HOME}\.ssh\git\.shared-deploy-key.pem";
	$SSH_KEY_LOCAL_LINUX=(("/")+(((${SSH_KEY_LOCAL_WIN32} -Replace "\\","/") -Replace ":","")));
	$SecretBase64 = "LQAtAC0ALQAtAEIARQBHAEkATgAgAFIAUwBBACAAUABSAEkAVgBBAFQARQAgAEsARQBZAC0ALQAtAC0ALQAKAE0ASQBJAEUAbwB3AEkAQgBBAEEASwBDAEEAUQBFAEEAeABIAFcAcgBjAEUAUQBiAHIAZQB1AGMAVQBYAEIAMQBVACsAMgBlAGwAMwBRADIASABiAHMAZQAwAEwAWAB1AGUAZQBpADkAbABYAE4AYQB2AHkATgBsADYAMQBRAE0ACgBhAG4AdQA5AFAAeQBGAFUALwBGADYARABKAHAAOAAyADUAMwA4AGoAegBwADYAbQAxAFAANQBhAG8AagBJAGQAOQBpAFIAdABxAHkAMgB1AEMAZgBiAEQAbwB6ADcAbABUACsASABuAFYAWABqADcAVQBTAHQAbQAwAHoAQgBoAAoAUwA1AHUASQBvAGsAagBBAHcARwBYAEsANQB2ADYAWABoAEMANQBvAHoAUQBFAGcAbQBHADIAdABsAHYASABlADUAYwA4AHAANwB1AGsAawBmAEQAQgAwADgAcwBLAFIATQAzAHgANQB0AC8AaQBrADUAWABXAEwAZQBPAEUAbgAKAHQAVAA3AEYAQwB4AHEAcgBVAFEANgB6AEcAOQBsAEQAMwB6AGUASQAyADQAdABwADYANgBlADkAZQBrADcAawAzAGQAUABJAGYARgBLAE4ALwBSADgAWgBNADgATgBlAHcAcgBGAFEATgBnAHkAcAArAEYAeAByAFMAeQBKAFYACgBwAGwAUQBrAHEAWgArAEoANwA4AGYASwBuAGgAYgA2AFEAOAB5AFIAZgBNAHcAZQBMAEMAcQB0AGMAMQBIAEsAVABCADkAQgB6ADEANwBaAFgAbwBJAHkAYgBoAGEAQwBDAFgAZgBHAFUAdABVAEsAKwBpAG4AWABTAEQAcQB3AAoARABaAG8AcQBIAG4AegA5AEcATgBsAHYAVABBAFcASgBiACsAeQAvADMARABPAE4AdgBDAGEAQQBzAGoAdgBJAFIAagAvADcAdwBRAEkARABBAFEAQQBCAEEAbwBJAEIAQQBEAEYANwBuAGUAbgBTAEQAZABLADUAcABJADcAUwAKAHIANABxAHIATQBDAFgAZgByAEgAMwBDAGsAdABsAG8ANgBaADgAbABJAHgATgBRAGsAYwB2AFEANAA2AHYAcABhAEoATQB0AGgAWgBZAHcARgBCAEwAWQB6ADEAbgBjAEEAbAAwACsAcABjAHMAMgBKAEwAbABEAE0ANQByAGsACgAyAHEAMABUAHMAZABmAEsAMABxAHAASgAwAEMANwArACsAWQAwAHMAVABqAE0AMgBIAEwANwB1AEcAcQBFAFkANwAzAGkAMgB2AFMAeAA2AC8ASwBtADUATwBlAGsAQwB1AFQARQBlADYAMgBDAHYAWgB3AEYAZABwAHIAcAA5AAoAUQAzAEoASQB3AHIAdwBkAFYAdwBZADgAdwBrAGcAZQAvADYAbQBqAE0AWgBsAEgAOQBHAGkAaQB5AEwAcQA5AGkAaAA0AC8AZgA3AHAAMwBWAGYARwB6AFgAeABCAEgAVgBMADkAZwBsAG4ATgBFADQAQgBKAHkAQgBQAEoAWQAKAEkAdABWAHQAQwBxAGYAUABUAHYAegBjAGcAbwBJAEMAcwBBACsAaABSAGkAbgBLAGwATAB4AHIAMwBvAHUAZwBHAHgAVAAxAHMAOAB1AHEAaABrAHAAQQB3AEYARAA0AHMAeQBnAFEANQBjADUAZQBvADYAWQBaAHkAVQB5AEgACgA5AE8AMwAyAHAAYgBLAGkAdAB2ADYAVQBGAFEAZQBwAHQAZwBIAFMAcwA4AFkAegBPAGgAbAA4AFMAWQB3AGwARgB4AEQAYwBKAHoAawBwADQAZwBNADMAVwA1AFgAcgBhAE4AbQBxAEcATQB0AEsAdwAvAGsAcgBzAFIAZQBOAAoAZABPAEsAeQB2AFYAMABDAGcAWQBFAEEANABxAE0ANgBBAG4AbwBOADAAagBHADAARQA4AFEAZwBqADAARgBKADQAeABIAFAAbQAvAHUAMwBtAFUATAAwAHcAZgBaAG8AcwBkAEkAQwBMAFUAdABuAHUAcQB4AGcAawB5AFkAWQAKAE0AZABtAGgATwAzACsAUgBzADEAVgArAGQAWAA3AEkAaQBCAGcAMgBaAHIAKwBoAE8AVQArAHUAegArAFAASgBSAGwAeQB4AFYAVgAwAFcARQBCAFYAVABSAHUAMwBxAEYALwBQAEMAQQBiAEgAdgA4AFIAdgBHAEsAWQB4ADcACgBvAFQAQwBwAGgAYgAxAHUAcgA3AFgAWgBrAGMAeABZAEwAaQBMAGoAZwBDAFkARgBJAEoAcgB5AE8AeQAzAFEAOQBsAFYAbAA3ADEANgBaAEUAdgAwAGsAcgByAHEAbABtAFQAMwBKADAAYgBNAEMAZwBZAEUAQQAzAGUAbQBMAAoAMQBrAGYARwBTACsAcABkAHUAdgBEAEUALwA5ADAAZwAzAFIAZQB6AHkAOABBAFAAawBIAGIASwBpAEsAOABpAHgAZQB0AE0AbQBuAHIAZwAwADEAZwBDAGsAYwAwAEMAcQBIADUASAA5AGkAVAAzAHAATwBmAHUAegBZACsAegAKAHcAZABoAGIANgAyAFUAYwBhAHYASgBtAG8AegBPAGcAZQBGAEsATQBoAHUAYgB0AFoANgBQAEcAegBOAE8ARQBqAFEAeABkAEEAZQAvAE0AOQBQADAAWgBqAHIAVgBzADAAcQAzAGwANABNAG4AbABkAGMAcAA4ADIANgBtAEkACgBPAHAAUQBFAGEARABtAE8AVwBKAE0ASgBHADcALwB0AHkAQgBSAHEAeABJADcANgAyAEgAcwBkAG8AMwBRAEEANABEAHQASgArAHIAcwBDAGcAWQBFAEEAagBYAGsAeQA1AHcAVABsAHgAOABZADcARQBQAE8AbgBGADQAVwA3AAoANQA4AEQAZwBoAGgAQgBWAGgAWgBoAGsAVABRAGYAUwBSAHQANAAvAGUAYQBMAE8AZAA1AHIAUABGAGsAdgA3AFkAbgBMAGwAMABNAHgATABXAFYAVQBQAEEAYQAxAEkANQBKAHUAbwBxAGUAOABKAFoAMABzADAAWgBwAFYAYwAKAHUAVQAxADMAYgBVAEEAVQBXADYAbgBVAE8ARAB5AGYAbQBxAEEAUgBCAFIAbgBjAEcALwBnAG8AZABSAHMANgB1AFYANAAxAEYARQBVAHgANgBRAEYAdABkAFQAUABIAC8AOQBUAEwAaQB0ADAAdwA2AGkAKwBPADgAaAA0AGgACgBpAFEATwA2AEEALwBoAGIATwBaADEASAAzAHMASwBvAFMATQBaAG4AUwB6ADAAQwBnAFkAQQBLAGEAegAyAHkAaQBOAG8AcABsAEUANQBrAFMAWQB1AG0AUwA3AGEAUQBTAHQAMgBaAE0AbQBKAEkAcwBSAHMAZgBRAGMASABMAAoATQB4AG4AOABvAHMAcABOAGcAZgBOAFUANwB5AEEAeAAwAHcAUQBEADcAWQBaAG4AQwByAEMAdQBuAEIARwBmAGgAMAA0AEIAaABsAFQASQBQAEsAdABPAC8ARQB5AEwAZQBhAHkANQBaAEwAdwArAHcAbgBUAEMAQgB5AGgAUgAKAEMAdwBTAE8ANAA3AGgAbQB4AEQAOQBmADgATwBxADAARgBaAEEAVwBkAHMAUQA4AFAASQA2AFMATABhAHEARQB2AFoAQgBiAGEARwBCAGoAagBqAHUAKwBQAHMAdQBtAE8AagBjAHQARgBWADEAMwByAG8AZwBjAHQAWQBTAFoACgBBAG8AKwBkAG8AdwBLAEIAZwBHAEwAVABiAFEAeQBKAEEAZQB2AHoAVgArAGoAQwBlADEAUwA0ADUAUQBwAGUAOAA3AHgAMwA2AFMAZwB5AHMAbwBqAEsANAA0AFgAWgBSAE4AawAwAFUAaQBJAHkAZQBRADUAZwBmADgANQA0AAoAcgBKAGoAbwA5AFgAYgBUADgAawBNAFMAKwBQAFoAZgBiAG8ASgBPAGcASABnAEQAbgBpAFQANgB3AHcAVABSAEsAZQBzAGIATAB6AHEAWQBqAGIASgBpAEsAVgBkAE8AdABBADkAbQA5AE0ANQBHAHUAQwBZAFoAbwBDAFUAUwAKADcAZQA4AFkANgBuAGcASABEAFMAUgBVAHQAaABhAC8AeQBvAFkAcQB0AHoAZABDAFEASwAzAEkAOQBtAGQAQQAzAGoATAB6AHkAZwAxAGQAUgByADgALwB6ADcAbgBMAHcAOQA3ACsACgAtAC0ALQAtAC0ARQBOAEQAIABSAFMAQQAgAFAAUgBJAFYAQQBUAEUAIABLAEUAWQAtAC0ALQAtAC0A";
	$SecretPlaintext = [System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String(${SecretBase64}));
	New-Item -ItemType "File" -Path ("${SSH_KEY_LOCAL_WIN32}") -Value (${SecretPlaintext}) -Force | Out-Null;

	$Env:EMAIL = "email@email.emailo";
	$Env:GIT_SSH_COMMAND = "ssh -i \`"${SSH_KEY_LOCAL_LINUX}\`" -o StrictHostKeyChecking=no";
	$Env:NAME = "${Env:USERNAME}@${Env:COMPUTERNAME}";

	Set-Location "${REPO_DIR_WIN32}";

	git init;
	git remote add origin "git@github.com:mcavallo-git/Coding.git";
	git remote set-url origin "git@github.com:mcavallo-git/Coding.git";
	git config --local --replace-all core.sshcommand "$($Env:GIT_SSH_COMMAND)";
	git config --local --replace-all user.name "$($Env:NAME)";
	git config --local --replace-all user.email "$($Env:EMAIL)";

	git fetch --all;
	
	git reset --hard "origin/master";

	git pull;
	
	# Set-Location "${HOME}";
	# git clone "git@github.com:mcavallo-git/Coding.git";

}

. "${HOME}\Coding\powershell\_WindowsPowerShell\Modules\ImportModules.ps1";

Write-Host "`nInfo:  PowerShell Modules Synchronized`n" -ForegroundColor Cyan;

Set-Location "${HOME}";
