pipeline {
	agent {
		node {
			label "windows"
		}
	}
	stages {
		stage ('Install NuGet') {
			steps {
				powershell(
					returnStatus:true,
					script:'''
						$PackageProvider = "NuGet";
						If ((Get-PackageProvider -Name "${PackageProvider}" -ErrorAction "SilentlyContinue") -Eq $Null) {
							$ProtoBak=[System.Net.ServicePointManager]::SecurityProtocol;
							[System.Net.ServicePointManager]::SecurityProtocol=[System.Net.SecurityProtocolType]"Tls11,Tls12";
								Install-PackageProvider -Name ("${PackageProvider}") -Force -Confirm:$False; $InstallPackageProvider_ReturnCode = If($?){0}Else{1};  # Install-PackageProvider fails on default windows installs without at least TLS 1.1 as of 20200501T041624
							[System.Net.ServicePointManager]::SecurityProtocol=$ProtoBak;
						}
					'''
				)
			}
		}
		stage ('Install PolicyFileEditor') {
			steps {
				powershell(
					returnStatus:true,
					script:'''
						$PackageProvider = "NuGet";
						If ((Get-PackageProvider -Name "${PackageProvider}" -ErrorAction "SilentlyContinue") -Eq $Null) {
							$ProtoBak=[System.Net.ServicePointManager]::SecurityProtocol;
							[System.Net.ServicePointManager]::SecurityProtocol=[System.Net.SecurityProtocolType]"Tls11,Tls12";
								Install-Module -Name ("PolicyFileEditor") -Scope ("CurrentUser") -Force -AllowClobber -SkipPublisherCheck -Confirm:$False -ErrorAction SilentlyContinue;
							[System.Net.ServicePointManager]::SecurityProtocol=$ProtoBak;
						}
					'''
				)
			}
		}
	}
}


// ------------------------------------------------------------
//
// Citation(s)
//
//   stackoverflow.com  |  "Executing powershell command directly in jenkins pipeline - Stack Overflow"  |  https://stackoverflow.com/a/42576572
//
//   stackoverflow.com  |  "Using a Jenkins pipeline to checkout multiple git repos into same job - Stack Overflow"  |  https://stackoverflow.com/a/40225216
//
//   www.jfrog.com  |  "Scripted Pipeline Syntax - JFrog - JFrog Documentation"  |  https://www.jfrog.com/confluence/display/JFROG/Scripted+Pipeline+Syntax
//
//   www.jfrog.com  |  "Working With Pipeline Jobs in Jenkins - Artifactory 5.x - JFrog Wiki"  |  https://www.jfrog.com/confluence/display/RTF5X/Working+With+Pipeline+Jobs+in+Jenkins
//
//   www.jenkins.io  |  "Pipeline: Basic Steps"  |  https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/
//
//   www.jenkins.io  |  "Pipeline Examples"  |  https://www.jenkins.io/doc/pipeline/examples/
//
//   www.jenkins.io  |  "Pipeline Syntax"  |  https://www.jenkins.io/doc/book/pipeline/syntax/
//
//   www.jenkins.io  |  "Using a Jenkinsfile"  |  https://www.jenkins.io/doc/book/pipeline/jenkinsfile/
//
// ------------------------------------------------------------