pipeline {
	agent {
		node {
			label "windows"
		}
	}
	stages {
		stage ('Checkout') {
			steps {
				checkout([
					$class: 'GitSCM', 
					branches: [[name: 'BRANCH_NAME']], 
					doGenerateSubmoduleConfigurations: false, 
					extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'REPOSITORY_NAME']], 
					submoduleCfg: [], 
					userRemoteConfigs: [[credentialsId: 'JENKINS_CREDENTIAL_ID', url: 'REPOSITORY_URL']]
				])
			}
		}
		stage ('Run Script from Repo') {
			steps {
				powershell(
					returnStatus:true,
					script:'.\\REPOSITORY_NAME\\RELATIVE_PATH_TO_SCRIPT'
				)
			}
		}
	}
}


// ------------------------------------------------------------
//
// Citation(s)
//
//   stackoverflow.com  |  "Using a Jenkins pipeline to checkout multiple git repos into same job - Stack Overflow"  |  https://stackoverflow.com/a/40225216
//
//   stackoverflow.com  |  "Executing powershell command directly in jenkins pipeline - Stack Overflow"  |  https://stackoverflow.com/a/42576572
//
//   www.jfrog.com  |  "Scripted Pipeline Syntax - JFrog - JFrog Documentation"  |  https://www.jfrog.com/confluence/display/JFROG/Scripted+Pipeline+Syntax
//
//   www.jfrog.com  |  "Working With Pipeline Jobs in Jenkins - Artifactory 5.x - JFrog Wiki"  |  https://www.jfrog.com/confluence/display/RTF5X/Working+With+Pipeline+Jobs+in+Jenkins
//
//   www.jenkins.io  |  "Pipeline: Basic Steps"  |  https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/
//
//   www.jenkins.io  |  "Pipeline Examples"  |  https://www.jenkins.io/doc/pipeline/examples/
//
//   www.jenkins.io  |  "Pipeline Syntax"  |  https://www.jenkins.io/doc/book/pipeline/syntax/
//
//   www.jenkins.io  |  "Using a Jenkinsfile"  |  https://www.jenkins.io/doc/book/pipeline/jenkinsfile/
//
// ------------------------------------------------------------