Get-Command | Where-Object { $_.Module -Like 'Vmware*' }

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Answer-VMQuestion                                  11.5.0.... VMware.VimAutomation.Core
Alias           Apply-DrsRecommendation                            11.5.0.... VMware.VimAutomation.Core
Alias           Apply-ESXImageProfile                              6.7.0.1... VMware.DeployAutomation
Alias           Apply-VMHostProfile                                11.5.0.... VMware.VimAutomation.Core
Alias           Attach-Baseline                                    6.5.1.7... VMware.VumAutomation
Alias           Connect-HVServer                                   7.10.0.... VMware.VimAutomation.HorizonView
Alias           Connect-PIComputeInstance                          11.0.0.... VMware.VimAutomation.Cloud
Alias           Connect-PIDatacenter                               11.0.0.... VMware.VimAutomation.Cloud
Alias           Connect-VmcServer                                  11.5.0.... VMware.VimAutomation.Vmc
Alias           Detach-Baseline                                    6.5.1.7... VMware.VumAutomation
Alias           Disconnect-HVServer                                7.10.0.... VMware.VimAutomation.HorizonView
Alias           Disconnect-PIComputeInstance                       11.0.0.... VMware.VimAutomation.Cloud
Alias           Disconnect-PIDatacenter                            11.0.0.... VMware.VimAutomation.Cloud
Alias           Disconnect-VmcServer                               11.5.0.... VMware.VimAutomation.Vmc
Alias           Download-Patch                                     6.5.1.7... VMware.VumAutomation
Alias           Export-VM                                          11.5.0.... VMware.VimAutomation.Core
Alias           Get-DeployCommand                                  6.7.0.1... VMware.DeployAutomation
Alias           Get-ESX                                            11.5.0.... VMware.VimAutomation.Core
Alias           Get-HCXApplianceCompute                            11.5.0.... VMware.VimAutomation.Hcx
Alias           Get-HCXApplianceDatastore                          11.5.0.... VMware.VimAutomation.Hcx
Alias           Get-HCXApplianceDVS                                11.5.0.... VMware.VimAutomation.Hcx
Alias           Get-HCXApplianceNetwork                            11.5.0.... VMware.VimAutomation.Hcx
Alias           Get-PIAccessControlRule                            11.0.0.... VMware.VimAutomation.Cloud
Alias           Get-PINetworkAdapter                               11.0.0.... VMware.VimAutomation.Cloud
Alias           Get-PIUser                                         11.0.0.... VMware.VimAutomation.Cloud
Alias           Get-PIVApp                                         11.0.0.... VMware.VimAutomation.Cloud
Alias           Get-PIVAppNetwork                                  11.0.0.... VMware.VimAutomation.Cloud
Alias           Get-PIVAppStartRule                                11.0.0.... VMware.VimAutomation.Cloud
Alias           Get-PIVAppTemplate                                 11.0.0.... VMware.VimAutomation.Cloud
Alias           Get-PIVM                                           11.0.0.... VMware.VimAutomation.Cloud
Alias           Get-PIVMTemplate                                   11.0.0.... VMware.VimAutomation.Cloud
Alias           Get-PowerCLIDocumentation                          11.5.0.... VMware.VimAutomation.Core
Alias           Get-VC                                             11.5.0.... VMware.VimAutomation.Core
Alias           Get-VIServer                                       11.5.0.... VMware.VimAutomation.Core
Alias           Get-VIToolkitConfiguration                         11.5.0.... VMware.VimAutomation.Core
Alias           Get-VIToolkitVersion                               11.5.0.... VMware.VimAutomation.Core
Alias           Import-PIVAppTemplate                              11.0.0.... VMware.VimAutomation.Cloud
Alias           New-PIAccessControlRule                            11.0.0.... VMware.VimAutomation.Cloud
Alias           New-PIVApp                                         11.0.0.... VMware.VimAutomation.Cloud
Alias           New-PIVAppNetwork                                  11.0.0.... VMware.VimAutomation.Cloud
Alias           New-PIVAppTemplate                                 11.0.0.... VMware.VimAutomation.Cloud
Alias           New-PIVM                                           11.0.0.... VMware.VimAutomation.Cloud
Alias           Remediate-Inventory                                6.5.1.7... VMware.VumAutomation
Alias           Remove-PIAccessControlRule                         11.0.0.... VMware.VimAutomation.Cloud
Alias           Remove-PIVApp                                      11.0.0.... VMware.VimAutomation.Cloud
Alias           Remove-PIVAppNetwork                               11.0.0.... VMware.VimAutomation.Cloud
Alias           Remove-PIVAppTemplate                              11.0.0.... VMware.VimAutomation.Cloud
Alias           Repair-VsanObject                                  11.5.0.... VMware.VimAutomation.Storage
Alias           Restart-PIVApp                                     11.0.0.... VMware.VimAutomation.Cloud
Alias           Restart-PIVAppGuest                                11.0.0.... VMware.VimAutomation.Cloud
Alias           Restart-PIVM                                       11.0.0.... VMware.VimAutomation.Cloud
Alias           Restart-PIVMGuest                                  11.0.0.... VMware.VimAutomation.Cloud
Alias           Scan-Inventory                                     6.5.1.7... VMware.VumAutomation
Alias           Set-PIAccessControlRule                            11.0.0.... VMware.VimAutomation.Cloud
Alias           Set-PINetworkAdapter                               11.0.0.... VMware.VimAutomation.Cloud
Alias           Set-PIVApp                                         11.0.0.... VMware.VimAutomation.Cloud
Alias           Set-PIVAppNetwork                                  11.0.0.... VMware.VimAutomation.Cloud
Alias           Set-PIVAppStartRule                                11.0.0.... VMware.VimAutomation.Cloud
Alias           Set-PIVAppTemplate                                 11.0.0.... VMware.VimAutomation.Cloud
Alias           Set-VIToolkitConfiguration                         11.5.0.... VMware.VimAutomation.Core
Alias           Shutdown-VMGuest                                   11.5.0.... VMware.VimAutomation.Core
Alias           Stage-Patch                                        6.5.1.7... VMware.VumAutomation
Alias           Start-PIVApp                                       11.0.0.... VMware.VimAutomation.Cloud
Alias           Start-PIVM                                         11.0.0.... VMware.VimAutomation.Cloud
Alias           Stop-PIVApp                                        11.0.0.... VMware.VimAutomation.Cloud
Alias           Stop-PIVAppGuest                                   11.0.0.... VMware.VimAutomation.Cloud
Alias           Stop-PIVM                                          11.0.0.... VMware.VimAutomation.Cloud
Alias           Stop-PIVMGuest                                     11.0.0.... VMware.VimAutomation.Cloud
Alias           Suspend-CIVAppGuest                                11.0.0.... VMware.VimAutomation.Cloud
Alias           Suspend-PIVApp                                     11.0.0.... VMware.VimAutomation.Cloud
Alias           Suspend-PIVAppGuest                                11.0.0.... VMware.VimAutomation.Cloud
Alias           Suspend-PIVM                                       11.0.0.... VMware.VimAutomation.Cloud
Function        Get-CisCommand                                     11.5.0.... VMware.VimAutomation.Cis.Core
Function        Get-InstallPath                                    11.5.0.... VMware.VimAutomation.Sdk
Function        Get-PowerCLICommunity                              11.5.0.... VMware.VimAutomation.Sdk
Function        Get-PowerCLIHelp                                   11.5.0.... VMware.VimAutomation.Sdk
Function        Get-PSVersion                                      11.5.0.... VMware.VimAutomation.Sdk
Function        Get-VICommand                                      11.5.0.... VMware.VimAutomation.Core
Function        HookGetViewAutoCompleter                           11.5.0.... VMware.VimAutomation.Core
Function        New-DatastoreDrive                                 11.5.0.... VMware.VimAutomation.Core
Function        New-VIInventoryDrive                               11.5.0.... VMware.VimAutomation.Core
Function        TabExpansion2                                      11.5.0.... VMware.VimAutomation.Core
Function        Update-VmfsDatastore                               1.3.0.0    VMware.VimAutomation.StorageUtility
Cmdlet          Add-CIDatastore                                    11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Add-DeployRule                                     6.7.0.1... VMware.DeployAutomation
Cmdlet          Add-EntityBaseline                                 6.5.1.7... VMware.VumAutomation
Cmdlet          Add-EsxSoftwareDepot                               6.7.0.1... VMware.ImageBuilder
Cmdlet          Add-EsxSoftwarePackage                             6.7.0.1... VMware.ImageBuilder
Cmdlet          Add-KeyManagementServer                            11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Add-PassthroughDevice                              11.5.0.... VMware.VimAutomation.Core
Cmdlet          Add-ProxyServer                                    6.7.0.1... VMware.DeployAutomation
Cmdlet          Add-ScriptBundle                                   6.7.0.1... VMware.DeployAutomation
Cmdlet          Add-VDSwitchPhysicalNetworkAdapter                 11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Add-VDSwitchVMHost                                 11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Add-VirtualSwitchPhysicalNetworkAdapter            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Add-VmcSddcHost                                    11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Add-VMHost                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Add-VMHostNtpServer                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Add-VsanObjectToRepairQueue                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Compare-EsxImageProfile                            6.7.0.1... VMware.ImageBuilder
Cmdlet          Connect-CIServer                                   11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Connect-CisServer                                  11.5.0.... VMware.VimAutomation.Cis.Core
Cmdlet          Connect-HCXServer                                  11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Connect-NsxtServer                                 11.5.0.... VMware.VimAutomation.Nsxt
Cmdlet          Connect-OMServer                                   10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Connect-SrmServer                                  11.5.0.... VMware.VimAutomation.Srm
Cmdlet          Connect-VIServer                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Connect-Vmc                                        11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Copy-ContentLibraryItem                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Copy-DatastoreItem                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Copy-DeployRule                                    6.7.0.1... VMware.DeployAutomation
Cmdlet          Copy-HardDisk                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Copy-Patch                                         6.5.1.7... VMware.VumAutomation
Cmdlet          Copy-VDisk                                         11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Copy-VMGuestFile                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Disconnect-CIServer                                11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Disconnect-CisServer                               11.5.0.... VMware.VimAutomation.Cis.Core
Cmdlet          Disconnect-HCXServer                               11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Disconnect-NsxtServer                              11.5.0.... VMware.VimAutomation.Nsxt
Cmdlet          Disconnect-OMServer                                10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Disconnect-SrmServer                               11.5.0.... VMware.VimAutomation.Srm
Cmdlet          Disconnect-VIServer                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Disconnect-Vmc                                     11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Dismount-Tools                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Export-AutoDeployState                             6.7.0.1... VMware.DeployAutomation
Cmdlet          Export-ContentLibraryItem                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Export-EsxImageProfile                             6.7.0.1... VMware.ImageBuilder
Cmdlet          Export-SpbmStoragePolicy                           11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Export-VApp                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Export-VDPortGroup                                 11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Export-VDSwitch                                    11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Export-VMHostProfile                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Format-VMHostDiskPartition                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-AdvancedSetting                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-AlarmAction                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-AlarmActionTrigger                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-AlarmDefinition                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-AlarmTrigger                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-Annotation                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-AwsAccount                                     11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Get-AwsVpcSubnet                                   11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Get-Baseline                                       6.5.1.7... VMware.VumAutomation
Cmdlet          Get-Catalog                                        11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CDDrive                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-CIAccessControlRule                            11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CIDatastore                                    11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CINetworkAdapter                               11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CIRole                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CisService                                     11.5.0.... VMware.VimAutomation.Cis.Core
Cmdlet          Get-CIUser                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CIVApp                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CIVAppNetwork                                  11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CIVAppStartRule                                11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CIVAppTemplate                                 11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CIView                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CIVM                                           11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-CIVMTemplate                                   11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-Cluster                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-Compliance                                     6.5.1.7... VMware.VumAutomation
Cmdlet          Get-ContentLibrary                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-ContentLibraryItem                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-CustomAttribute                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-Datacenter                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-Datastore                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-DatastoreCluster                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-DeployOption                                   6.7.0.1... VMware.DeployAutomation
Cmdlet          Get-DeployRule                                     6.7.0.1... VMware.DeployAutomation
Cmdlet          Get-DeployRuleSet                                  6.7.0.1... VMware.DeployAutomation
Cmdlet          Get-DrsClusterGroup                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-DrsRecommendation                              11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-DrsRule                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-DrsVMHostRule                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-EdgeGateway                                    11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-ErrorReport                                    11.5.0.... VMware.VimAutomation.Sdk
Cmdlet          Get-EsxCli                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-EsxImageProfile                                6.7.0.1... VMware.ImageBuilder
Cmdlet          Get-EsxSoftwareDepot                               6.7.0.1... VMware.ImageBuilder
Cmdlet          Get-EsxSoftwarePackage                             6.7.0.1... VMware.ImageBuilder
Cmdlet          Get-EsxTop                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-EventType                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-ExternalNetwork                                11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-FloppyDrive                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-Folder                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-HAPrimaryVMHost                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-HardDisk                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-HCXAppliance                                   11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXComputeProfile                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXContainer                                   11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXDatastore                                   11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXGateway                                     11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXInterconnectStatus                          11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXInventoryCompute                            11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXInventoryDatastore                          11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXInventoryDVS                                11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXInventoryNetwork                            11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXJob                                         11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXMigration                                   11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXNetwork                                     11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXNetworkBacking                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXNetworkExtension                            11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXNetworkProfile                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXReplication                                 11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXReplicationSnapshot                         11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXService                                     11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXServiceMesh                                 11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXSite                                        11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXSitePairing                                 11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXStorageProfile                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-HCXVM                                          11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Get-Inventory                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-IScsiHbaTarget                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-KeyManagementServer                            11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-KmipClientCertificate                          11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-KmsCluster                                     11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-LicenseDataManager                             11.3.0.... VMware.VimAutomation.License
Cmdlet          Get-Log                                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-LogType                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-Media                                          11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-Metric                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-NetworkAdapter                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-NetworkPool                                    11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-NfsUser                                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-NicTeamingPolicy                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-NsxtPolicyService                              11.5.0.... VMware.VimAutomation.Nsxt
Cmdlet          Get-NsxtService                                    11.5.0.... VMware.VimAutomation.Nsxt
Cmdlet          Get-OMAlert                                        10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Get-OMAlertDefinition                              10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Get-OMAlertSubType                                 10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Get-OMAlertType                                    10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Get-OMRecommendation                               10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Get-OMResource                                     10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Get-OMStat                                         10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Get-OMStatKey                                      10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Get-OMUser                                         10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Get-Org                                            11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-OrgNetwork                                     11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-OrgVdc                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-OrgVdcNetwork                                  11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-OSCustomizationNicMapping                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-OSCustomizationSpec                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-OvfConfiguration                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-PassthroughDevice                              11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-Patch                                          6.5.1.7... VMware.VumAutomation
Cmdlet          Get-PatchBaseline                                  6.5.1.7... VMware.VumAutomation
Cmdlet          Get-PowerCLIConfiguration                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-PowerCLIVersion                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-ProviderVdc                                    11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Get-ProxyServer                                    6.7.0.1... VMware.DeployAutomation
Cmdlet          Get-ResourcePool                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-ScriptBundle                                   6.7.0.1... VMware.DeployAutomation
Cmdlet          Get-ScsiController                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-ScsiLun                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-ScsiLunPath                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-SecurityInfo                                   11.0.0.... VMware.VimAutomation.Security
Cmdlet          Get-SecurityPolicy                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-Snapshot                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-SpbmCapability                                 11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-SpbmCompatibleStorage                          11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-SpbmEntityConfiguration                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-SpbmFaultDomain                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-SpbmPointInTimeReplica                         11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-SpbmReplicationGroup                           11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-SpbmReplicationPair                            11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-SpbmStoragePolicy                              11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-SpbmView                                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-Stat                                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-StatInterval                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-StatType                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-Tag                                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-TagAssignment                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-TagCategory                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-Task                                           11.5.0.... VMware.VimAutomation.Common
Cmdlet          Get-Template                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-UsbDevice                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VAIOFilter                                     11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VApp                                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VasaProvider                                   11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VasaStorageArray                               11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VDBlockedPolicy                                11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Get-VDisk                                          11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VDPort                                         11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Get-VDPortgroup                                    11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Get-VDPortgroupOverridePolicy                      11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Get-VDSecurityPolicy                               11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Get-VDSwitch                                       11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Get-VDSwitchPrivateVlan                            11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Get-VDTrafficShapingPolicy                         11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Get-VDUplinkLacpPolicy                             11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Get-VDUplinkTeamingPolicy                          11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Get-VIAccount                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VICredentialStoreItem                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VIEvent                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-View                                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VIObjectByVIView                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VIPermission                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VIPrivilege                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VIProperty                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VIRole                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VirtualNetwork                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VirtualPortGroup                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VirtualSwitch                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VM                                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VmcSddc                                        11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Get-VmcSddcNetworkService                          11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Get-VmcService                                     11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Get-VMGuest                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHost                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostAccount                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostAdvancedConfiguration                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostAttributes                               6.7.0.1... VMware.DeployAutomation
Cmdlet          Get-VMHostAuthentication                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostAvailableTimeZone                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostDiagnosticPartition                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostDisk                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostDiskPartition                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostFirewallDefaultPolicy                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostFirewallException                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostFirmware                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostHardware                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostHba                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostImageProfile                             6.7.0.1... VMware.DeployAutomation
Cmdlet          Get-VMHostMatchingRules                            6.7.0.1... VMware.DeployAutomation
Cmdlet          Get-VMHostModule                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostNetwork                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostNetworkAdapter                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostNtpServer                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostPatch                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostPciDevice                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostProfile                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostProfileImageCacheConfiguration           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostProfileRequiredInput                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostProfileStorageDeviceConfiguration        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostProfileUserConfiguration                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostProfileVmPortGroupConfiguration          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostRoute                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostService                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostSnmp                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostStartPolicy                              11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostStorage                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMHostSysLogServer                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMQuestion                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMResourceConfiguration                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VMStartPolicy                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Get-VsanClusterConfiguration                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanComponent                                  11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanDisk                                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanDiskGroup                                  11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanEnterMaintenanceModeReport                 11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanEvacuationPlan                             11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanFaultDomain                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanIscsiInitiatorGroup                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanIscsiInitiatorGroupTargetAssociation       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanIscsiLun                                   11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanIscsiTarget                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanObject                                     11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanResyncingComponent                         11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanResyncingOverview                          11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanRuntimeInfo                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanSpaceUsage                                 11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanStat                                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VsanView                                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Get-VTpm                                           11.0.0.... VMware.VimAutomation.Security
Cmdlet          Get-VTpmCertificate                                11.0.0.... VMware.VimAutomation.Security
Cmdlet          Get-VTpmCSR                                        11.0.0.... VMware.VimAutomation.Security
Cmdlet          Import-AutoDeployState                             6.7.0.1... VMware.DeployAutomation
Cmdlet          Import-CIVApp                                      11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Import-CIVAppTemplate                              11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Import-SpbmStoragePolicy                           11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Import-VApp                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Import-VMHostProfile                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Install-VMHostPatch                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Invoke-DrsRecommendation                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Invoke-VMHostProfile                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Invoke-VMScript                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Mount-Tools                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-Cluster                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-Datacenter                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-Datastore                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-Folder                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-HardDisk                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-Inventory                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-ResourcePool                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-Template                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-VApp                                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-VDisk                                         11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Move-VM                                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Move-VMHost                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-AdvancedSetting                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-AlarmAction                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-AlarmActionTrigger                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-AlarmDefinition                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-AlarmTrigger                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-CDDrive                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-CIAccessControlRule                            11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          New-CIVApp                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          New-CIVAppNetwork                                  11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          New-CIVAppTemplate                                 11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          New-CIVM                                           11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          New-Cluster                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-ContentLibrary                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-ContentLibraryItem                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-CustomAttribute                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-Datacenter                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-Datastore                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-DatastoreCluster                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-DeployRule                                     6.7.0.1... VMware.DeployAutomation
Cmdlet          New-DrsClusterGroup                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-DrsRule                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-DrsVMHostRule                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-EsxImageProfile                                6.7.0.1... VMware.ImageBuilder
Cmdlet          New-FloppyDrive                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-Folder                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-HardDisk                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-HCXAppliance                                   11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXComputeProfile                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXComputeProfileDVS                           11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXComputeProfileNetwork                       11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXMigration                                   11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXNetworkExtension                            11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXNetworkMapping                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXNetworkProfile                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXReplication                                 11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXSentinelBundle                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXServiceMesh                                 11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXServiceMeshDVS                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXSitePairing                                 11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-HCXStaticRoute                                 11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          New-IScsiHbaTarget                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-KmipClientCertificate                          11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-NetworkAdapter                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-NfsUser                                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-Org                                            11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          New-OrgNetwork                                     11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          New-OrgVdc                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          New-OrgVdcNetwork                                  11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          New-OSCustomizationNicMapping                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-OSCustomizationSpec                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-PatchBaseline                                  6.5.1.7... VMware.VumAutomation
Cmdlet          New-ResourcePool                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-ScsiController                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-Snapshot                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-SpbmRule                                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-SpbmRuleSet                                    11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-SpbmStoragePolicy                              11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-StatInterval                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-Tag                                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-TagAssignment                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-TagCategory                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-Template                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VAIOFilter                                     11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-VApp                                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VasaProvider                                   11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-VcsOAuthSecurityContext                        11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          New-VDisk                                          11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-VDPortgroup                                    11.2.0.... VMware.VimAutomation.Vds
Cmdlet          New-VDSwitch                                       11.2.0.... VMware.VimAutomation.Vds
Cmdlet          New-VDSwitchPrivateVlan                            11.2.0.... VMware.VimAutomation.Vds
Cmdlet          New-VICredentialStoreItem                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VIPermission                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VIProperty                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VIRole                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VirtualPortGroup                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VirtualSwitch                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VISamlSecurityContext                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VM                                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VmcSddc                                        11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          New-VMHostAccount                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VMHostNetworkAdapter                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VMHostProfile                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VMHostProfileVmPortGroupConfiguration          11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VMHostRoute                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          New-VsanDisk                                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-VsanDiskGroup                                  11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-VsanFaultDomain                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-VsanIscsiInitiatorGroup                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-VsanIscsiInitiatorGroupTargetAssociation       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-VsanIscsiLun                                   11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-VsanIscsiTarget                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          New-VTpm                                           11.0.0.... VMware.VimAutomation.Security
Cmdlet          Open-VMConsoleWindow                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-AdvancedSetting                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-AlarmAction                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-AlarmActionTrigger                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-AlarmDefinition                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-Baseline                                    6.5.1.7... VMware.VumAutomation
Cmdlet          Remove-CDDrive                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-CIAccessControlRule                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Remove-CIVApp                                      11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Remove-CIVAppNetwork                               11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Remove-CIVAppTemplate                              11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Remove-Cluster                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-ContentLibrary                              11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-ContentLibraryItem                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-CustomAttribute                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-Datacenter                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-Datastore                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-DatastoreCluster                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-DeployRule                                  6.7.0.1... VMware.DeployAutomation
Cmdlet          Remove-DrsClusterGroup                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-DrsRule                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-DrsVMHostRule                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-EntityBaseline                              6.5.1.7... VMware.VumAutomation
Cmdlet          Remove-EsxImageProfile                             6.7.0.1... VMware.ImageBuilder
Cmdlet          Remove-EsxSoftwareDepot                            6.7.0.1... VMware.ImageBuilder
Cmdlet          Remove-EsxSoftwarePackage                          6.7.0.1... VMware.ImageBuilder
Cmdlet          Remove-FloppyDrive                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-Folder                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-HardDisk                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-HCXAppliance                                11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Remove-HCXComputeProfile                           11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Remove-HCXNetworkExtension                         11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Remove-HCXNetworkProfile                           11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Remove-HCXReplication                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Remove-HCXServiceMesh                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Remove-HCXSitePairing                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Remove-Inventory                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-IScsiHbaTarget                              11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-KeyManagementServer                         11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-NetworkAdapter                              11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-NfsUser                                     11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-Org                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Remove-OrgNetwork                                  11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Remove-OrgVdc                                      11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Remove-OrgVdcNetwork                               11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Remove-OSCustomizationNicMapping                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-OSCustomizationSpec                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-PassthroughDevice                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-ProxyServer                                 6.7.0.1... VMware.DeployAutomation
Cmdlet          Remove-ResourcePool                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-ScriptBundle                                6.7.0.1... VMware.DeployAutomation
Cmdlet          Remove-Snapshot                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-SpbmStoragePolicy                           11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-StatInterval                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-Tag                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-TagAssignment                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-TagCategory                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-Template                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-UsbDevice                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VAIOFilter                                  11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-VApp                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VasaProvider                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-VDisk                                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-VDPortGroup                                 11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Remove-VDSwitch                                    11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Remove-VDSwitchPhysicalNetworkAdapter              11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Remove-VDSwitchPrivateVlan                         11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Remove-VDSwitchVMHost                              11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Remove-VICredentialStoreItem                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VIPermission                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VIProperty                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VIRole                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VirtualPortGroup                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VirtualSwitch                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VirtualSwitchPhysicalNetworkAdapter         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VM                                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VmcSddc                                     11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Remove-VmcSddcHost                                 11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Remove-VMHost                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VMHostAccount                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VMHostNetworkAdapter                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VMHostNtpServer                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VMHostProfile                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VMHostProfileVmPortGroupConfiguration       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VMHostRoute                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Remove-VsanDisk                                    11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-VsanDiskGroup                               11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-VsanFaultDomain                             11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-VsanIscsiInitiatorGroup                     11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-VsanIscsiInitiatorGroupTargetAssociation    11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-VsanIscsiLun                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-VsanIscsiTarget                             11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Remove-VTpm                                        11.0.0.... VMware.VimAutomation.Security
Cmdlet          Repair-DeployImageCache                            6.7.0.1... VMware.DeployAutomation
Cmdlet          Repair-DeployRuleSetCompliance                     6.7.0.1... VMware.DeployAutomation
Cmdlet          Restart-CIVApp                                     11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Restart-CIVAppGuest                                11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Restart-CIVM                                       11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Restart-CIVMGuest                                  11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Restart-VM                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Restart-VMGuest                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Restart-VMHost                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Restart-VMHostService                              11.5.0.... VMware.VimAutomation.Core
Cmdlet          Resume-HCXReplication                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Search-Cloud                                       11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-AdvancedSetting                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-AlarmDefinition                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-Annotation                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-CDDrive                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-CIAccessControlRule                            11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-CINetworkAdapter                               11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-CIVApp                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-CIVAppNetwork                                  11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-CIVAppStartRule                                11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-CIVAppTemplate                                 11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-Cluster                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-ContentLibrary                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-ContentLibraryItem                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-CustomAttribute                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-Datacenter                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-Datastore                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-DatastoreCluster                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-DeployOption                                   6.7.0.1... VMware.DeployAutomation
Cmdlet          Set-DeployRule                                     6.7.0.1... VMware.DeployAutomation
Cmdlet          Set-DeployRuleSet                                  6.7.0.1... VMware.DeployAutomation
Cmdlet          Set-DrsClusterGroup                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-DrsRule                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-DrsVMHostRule                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-EsxImageProfile                                6.7.0.1... VMware.ImageBuilder
Cmdlet          Set-ESXImageProfileAssociation                     6.7.0.1... VMware.DeployAutomation
Cmdlet          Set-FloppyDrive                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-Folder                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-HardDisk                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-HCXAppliance                                   11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Set-HCXComputeProfile                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Set-HCXMigration                                   11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Set-HCXNetworkProfile                              11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Set-HCXReplication                                 11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Set-HCXServiceMesh                                 11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Set-IScsiHbaTarget                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-KeyManagementServer                            11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-KmsCluster                                     11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-NetworkAdapter                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-NfsUser                                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-NicTeamingPolicy                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-OMAlert                                        10.0.0.... VMware.VimAutomation.vROps
Cmdlet          Set-Org                                            11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-OrgNetwork                                     11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-OrgVdc                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-OrgVdcNetwork                                  11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Set-OSCustomizationNicMapping                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-OSCustomizationSpec                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-PatchBaseline                                  6.5.1.7... VMware.VumAutomation
Cmdlet          Set-PowerCLIConfiguration                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-ResourcePool                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-ScriptBundleAssociation                        6.7.0.1... VMware.DeployAutomation
Cmdlet          Set-ScsiController                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-ScsiLun                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-ScsiLunPath                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-SecurityPolicy                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-Snapshot                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-SpbmEntityConfiguration                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-SpbmStoragePolicy                              11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-StatInterval                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-Tag                                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-TagCategory                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-Template                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VAIOFilter                                     11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-VApp                                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VDBlockedPolicy                                11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Set-VDisk                                          11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-VDPort                                         11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Set-VDPortgroup                                    11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Set-VDPortgroupOverridePolicy                      11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Set-VDSecurityPolicy                               11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Set-VDSwitch                                       11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Set-VDTrafficShapingPolicy                         11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Set-VDUplinkLacpPolicy                             11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Set-VDUplinkTeamingPolicy                          11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Set-VDVlanConfiguration                            11.2.0.... VMware.VimAutomation.Vds
Cmdlet          Set-VIPermission                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VIRole                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VirtualPortGroup                               11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VirtualSwitch                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VM                                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VmcSddc                                        11.5.0.... VMware.VimAutomation.Vmc
Cmdlet          Set-VMHost                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostAccount                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostAdvancedConfiguration                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostAuthentication                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostDiagnosticPartition                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostFirewallDefaultPolicy                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostFirewallException                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostFirmware                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostHba                                      11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostModule                                   11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostNetwork                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostNetworkAdapter                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostProfile                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostProfileImageCacheConfiguration           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostProfileStorageDeviceConfiguration        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostProfileUserConfiguration                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostProfileVmPortGroupConfiguration          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostRoute                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostService                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostSnmp                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostStartPolicy                              11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostStorage                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMHostSysLogServer                             11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMQuestion                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMResourceConfiguration                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VMStartPolicy                                  11.5.0.... VMware.VimAutomation.Core
Cmdlet          Set-VsanClusterConfiguration                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-VsanFaultDomain                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-VsanIscsiInitiatorGroup                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-VsanIscsiLun                                   11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-VsanIscsiTarget                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Set-VTpm                                           11.0.0.... VMware.VimAutomation.Security
Cmdlet          Start-CIVApp                                       11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Start-CIVM                                         11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Start-HCXMigration                                 11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Start-HCXReplication                               11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Start-SpbmReplicationFailover                      11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Start-SpbmReplicationPrepareFailover               11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Start-SpbmReplicationPromote                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Start-SpbmReplicationReverse                       11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Start-SpbmReplicationTestFailover                  11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Start-VApp                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Start-VM                                           11.5.0.... VMware.VimAutomation.Core
Cmdlet          Start-VMHost                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Start-VMHostService                                11.5.0.... VMware.VimAutomation.Core
Cmdlet          Start-VsanClusterDiskUpdate                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Start-VsanClusterRebalance                         11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Start-VsanEncryptionConfiguration                  11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Stop-CIVApp                                        11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Stop-CIVAppGuest                                   11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Stop-CIVM                                          11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Stop-CIVMGuest                                     11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Stop-SpbmReplicationTestFailover                   11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Stop-Task                                          11.5.0.... VMware.VimAutomation.Common
Cmdlet          Stop-VApp                                          11.5.0.... VMware.VimAutomation.Core
Cmdlet          Stop-VM                                            11.5.0.... VMware.VimAutomation.Core
Cmdlet          Stop-VMGuest                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Stop-VMHost                                        11.5.0.... VMware.VimAutomation.Core
Cmdlet          Stop-VMHostService                                 11.5.0.... VMware.VimAutomation.Core
Cmdlet          Stop-VsanClusterRebalance                          11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Suspend-CIVApp                                     11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Suspend-CIVM                                       11.0.0.... VMware.VimAutomation.Cloud
Cmdlet          Suspend-HCXReplication                             11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Suspend-VM                                         11.5.0.... VMware.VimAutomation.Core
Cmdlet          Suspend-VMGuest                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Suspend-VMHost                                     11.5.0.... VMware.VimAutomation.Core
Cmdlet          Switch-ActiveDeployRuleSet                         6.7.0.1... VMware.DeployAutomation
Cmdlet          Sync-Patch                                         6.5.1.7... VMware.VumAutomation
Cmdlet          Sync-SpbmReplicationGroup                          11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Test-Compliance                                    6.5.1.7... VMware.VumAutomation
Cmdlet          Test-DeployRuleSetCompliance                       6.7.0.1... VMware.DeployAutomation
Cmdlet          Test-HCXMigration                                  11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Test-HCXReplication                                11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Test-VMHostProfileCompliance                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Test-VMHostSnmp                                    11.5.0.... VMware.VimAutomation.Core
Cmdlet          Test-VsanClusterHealth                             11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Test-VsanNetworkPerformance                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Test-VsanStoragePerformance                        11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Test-VsanVMCreation                                11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Unlock-VM                                          11.0.0.... VMware.VimAutomation.Security
Cmdlet          Update-Entity                                      6.5.1.7... VMware.VumAutomation
Cmdlet          Update-Tools                                       11.5.0.... VMware.VimAutomation.Core
Cmdlet          Update-VsanHclDatabase                             11.5.0.... VMware.VimAutomation.Storage
Cmdlet          Wait-HCXJob                                        11.5.0.... VMware.VimAutomation.Hcx
Cmdlet          Wait-Task                                          11.5.0.... VMware.VimAutomation.Common
Cmdlet          Wait-Tools                                         11.5.0.... VMware.VimAutomation.Core
