# ------------------------------------------------------------
# PowerShell - ProgressPreference (hide progress bar, hide download progress, preference variable)
# ------------------------------------------------------------
#
#   $ProgressPreference
#   Determines how PowerShell responds to progress updates generated by a script, cmdlet, or provider, such as the progress bars generated by the Write-Progress cmdlet. The Write-Progress cmdlet creates progress bars that show a command's status.
#
#   The $ProgressPreference variable takes one of the ActionPreference enumeration values: SilentlyContinue, Stop, Continue, Inquire, Ignore, or Suspend.
#
#   The valid values are as follows:
#
#   Stop: Doesn't display the progress bar. Instead, it displays an error message and stops executing.
#   Inquire: Doesn't display the progress bar. Prompts for permission to continue. If you reply with Y or A, it displays the progress bar.
#   Continue: (Default) Displays the progress bar and continues with execution.
#   SilentlyContinue: Executes the command, but doesn't display the progress bar.
#
# ------------------------------------------------------------


$ProgressPreference='SilentlyContinue'; <# Greatly speeds up commands which show a progress bar by hiding it (especially for headless agents) #>


# ------------------------------------------------------------
#
# Citation(s)
#
#   learn.microsoft.com  |  "about Preference Variables - PowerShell | Microsoft Learn"  |  https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables#progresspreference
#
# ------------------------------------------------------------