@ECHO OFF
FOR /F "tokens=3-4" %%a IN ('QUERY SESSION %USERNAME%') DO (
	IF "%%b"=="Active" (
		SET USER_SESSION_ID=%%a
		SET USER_SESSION_STATE=%%b
	)
	IF "%%a"=="Disc" (
		SET USER_SESSION_STATE=%%a
	)
)
ECHO USER_SESSION_ID=[%USER_SESSION_ID%]
ECHO USER_SESSION_STATE=[%USER_SESSION_STATE%]
TIMEOUT /T 30