@ECHO OFF

REM   Process-ID  :::  Splashtop remote connection(s)
SET EXE_SPLASHTOP=SRFeature.exe

SET PID_SPLASHTOP=No
FOR /F "tokens=2-2" %%a IN ('TASKLIST /FI "IMAGENAME eq %EXE_SPLASHTOP%"') DO (
	SET PID_SPLASHTOP=%%a
)
ECHO PID_SPLASHTOP = %PID_SPLASHTOP%


REM		Kill Splashtop remote connection(s)
IF NOT %PID_SPLASHTOP%==No (
	REM TASKKILL /F /FI "IMAGENAME %EXE_SPLASHTOP%"
	TASKKILL /F /PID %PID_SPLASHTOP%
	TIMEOUT /T 1 > NUL
)

TIMEOUT /T 60
