@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION

SET QUICKNOTE_NOTIFICATION_AREA_EXE="ONENOTEM.EXE"
TASKLIST /FI "IMAGENAME eq %QUICKNOTE_NOTIFICATION_AREA_EXE%"
IF "!ERRORLEVEL!"=="0" ( REM PROGRAM CURRENTLY RUNNING
	TASKKILL /IM %QUICKNOTE_NOTIFICATION_AREA_EXE% /F
)

DEL "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\Send to OneNote*"

DEL "%USERPROFILE%\Documents\OneNote Notebooks\Quick Notes*.one"

TIMEOUT /T 30