--
-- MySQL Timezone Relativity-Comparators (inspection-only)
--           2019-04-22_13-20-18  :::  MCavallo  :::  https://github.com/mcavallo-git
--
SELECT

	@@global.time_zone
		AS 'Server TZ',
		
	@@session.time_zone
		AS 'Session TZ',

	CONCAT(
		SUBSTR(IF(LEFT(TIMEDIFF(NOW(),UTC_TIMESTAMP),1)='-', TIMEDIFF(NOW(),UTC_TIMESTAMP), CONCAT('+',TIMEDIFF(NOW(),UTC_TIMESTAMP))),1,3),
		SUBSTR(IF(LEFT(TIMEDIFF(NOW(),UTC_TIMESTAMP),1)='-', TIMEDIFF(NOW(),UTC_TIMESTAMP), CONCAT('+',TIMEDIFF(NOW(),UTC_TIMESTAMP))),5,2)
	)
		AS 'TZ_DIFF',


	SUBSTR(IF(LEFT(TIMEDIFF(NOW(),UTC_TIMESTAMP),1)='-', TIMEDIFF(NOW(),UTC_TIMESTAMP), CONCAT('+',TIMEDIFF(NOW(),UTC_TIMESTAMP))),1,6) 
		AS 'TZ_DIFF_COLON',


	CONVERT_TZ(
		NOW(),
		'+00:00',
		SUBSTR(IF(LEFT(TIMEDIFF(NOW(),UTC_TIMESTAMP),1)='-', TIMEDIFF(NOW(),UTC_TIMESTAMP), CONCAT('+',TIMEDIFF(NOW(),UTC_TIMESTAMP))),1,6)
	)
		AS 'NOW_converted_TO_utc',


	CONVERT_TZ(
		NOW(),
		SUBSTR(IF(LEFT(TIMEDIFF(NOW(),UTC_TIMESTAMP),1)='-', TIMEDIFF(NOW(),UTC_TIMESTAMP), CONCAT('+',TIMEDIFF(NOW(),UTC_TIMESTAMP))),1,6),
		'+00:00'
	)
		AS 'NOW_converted_FROM_utc'
	
;


-- -- Building the MySQL Timezone Relativitiy-Comparators
-- SELECT
-- 	IF(LEFT(TIMEDIFF(NOW(),UTC_TIMESTAMP),1)='-', TIMEDIFF(NOW(),UTC_TIMESTAMP), CONCAT('+',TIMEDIFF(NOW(),UTC_TIMESTAMP))) AS 'all',
-- 	SUBSTR(IF(LEFT(TIMEDIFF(NOW(),UTC_TIMESTAMP),1)='-', TIMEDIFF(NOW(),UTC_TIMESTAMP), CONCAT('+',TIMEDIFF(NOW(),UTC_TIMESTAMP))),1,3) AS '1_3',
-- 	SUBSTR(IF(LEFT(TIMEDIFF(NOW(),UTC_TIMESTAMP),1)='-', TIMEDIFF(NOW(),UTC_TIMESTAMP), CONCAT('+',TIMEDIFF(NOW(),UTC_TIMESTAMP))),4,1) AS '4_1',
-- 	SUBSTR(IF(LEFT(TIMEDIFF(NOW(),UTC_TIMESTAMP),1)='-', TIMEDIFF(NOW(),UTC_TIMESTAMP), CONCAT('+',TIMEDIFF(NOW(),UTC_TIMESTAMP))),5,2) AS '5_2'
