
SELECT
  TABLE_SCHEMA,
  TABLE_NAME,
  GROUP_CONCAT(COLUMN_NAME)
FROM
  INFORMATION_SCHEMA.COLUMNS
WHERE
  TABLE_SCHEMA IN ('DATABASE_1','DATABASE_2')
  AND TABLE_NAME='SAME_TABLENAME_FROM_MULTIPLE_DBS'
GROUP BY
  TABLE_SCHEMA
;
