SELECT 
	TRIGGER_SCHEMA,
	TRIGGER_NAME,
	ACTION_TIMING AS 'TIME', /* BEFORE, AFTER */
	EVENT_MANIPULATION AS 'EVENT', /* INSERT, UPDATE, DELETE */
	EVENT_OBJECT_SCHEMA AS 'TABLE',
	ACTION_STATEMENT AS 'DEFINITION'
FROM 
	information_schema.TRIGGERS
WHERE
	NOT TRIGGER_SCHEMA IN ('mysql','sys')
ORDER BY 
	TRIGGER_SCHEMA
