if [ -n "$(man git-add;)" ]; then man git-add > ~/man/git-add.man; fi; \
if [ -n "$(man git-am;)" ]; then man git-am > ~/man/git-am.man; fi; \
if [ -n "$(man git-archive;)" ]; then man git-archive > ~/man/git-archive.man; fi; \
if [ -n "$(man git-bisect;)" ]; then man git-bisect > ~/man/git-bisect.man; fi; \
if [ -n "$(man git-branch;)" ]; then man git-branch > ~/man/git-branch.man; fi; \
if [ -n "$(man git-bundle;)" ]; then man git-bundle > ~/man/git-bundle.man; fi; \
if [ -n "$(man git-checkout;)" ]; then man git-checkout > ~/man/git-checkout.man; fi; \
if [ -n "$(man git-cherry-pick;)" ]; then man git-cherry-pick > ~/man/git-cherry-pick.man; fi; \
if [ -n "$(man git-citool;)" ]; then man git-citool > ~/man/git-citool.man; fi; \
if [ -n "$(man git-clean;)" ]; then man git-clean > ~/man/git-clean.man; fi; \
if [ -n "$(man git-clone;)" ]; then man git-clone > ~/man/git-clone.man; fi; \
if [ -n "$(man git-commit;)" ]; then man git-commit > ~/man/git-commit.man; fi; \
if [ -n "$(man git-describe;)" ]; then man git-describe > ~/man/git-describe.man; fi; \
if [ -n "$(man git-diff;)" ]; then man git-diff > ~/man/git-diff.man; fi; \
if [ -n "$(man git-fetch;)" ]; then man git-fetch > ~/man/git-fetch.man; fi; \
if [ -n "$(man git-format-patch;)" ]; then man git-format-patch > ~/man/git-format-patch.man; fi; \
if [ -n "$(man git-gc;)" ]; then man git-gc > ~/man/git-gc.man; fi; \
if [ -n "$(man git-grep;)" ]; then man git-grep > ~/man/git-grep.man; fi; \
if [ -n "$(man git-gui;)" ]; then man git-gui > ~/man/git-gui.man; fi; \
if [ -n "$(man git-init;)" ]; then man git-init > ~/man/git-init.man; fi; \
if [ -n "$(man git-log;)" ]; then man git-log > ~/man/git-log.man; fi; \
if [ -n "$(man git-merge;)" ]; then man git-merge > ~/man/git-merge.man; fi; \
if [ -n "$(man git-mv;)" ]; then man git-mv > ~/man/git-mv.man; fi; \
if [ -n "$(man git-notes;)" ]; then man git-notes > ~/man/git-notes.man; fi; \
if [ -n "$(man git-pull;)" ]; then man git-pull > ~/man/git-pull.man; fi; \
if [ -n "$(man git-push;)" ]; then man git-push > ~/man/git-push.man; fi; \
if [ -n "$(man git-rebase;)" ]; then man git-rebase > ~/man/git-rebase.man; fi; \
if [ -n "$(man git-reset;)" ]; then man git-reset > ~/man/git-reset.man; fi; \
if [ -n "$(man git-revert;)" ]; then man git-revert > ~/man/git-revert.man; fi; \
if [ -n "$(man git-rm;)" ]; then man git-rm > ~/man/git-rm.man; fi; \
if [ -n "$(man git-shortlog;)" ]; then man git-shortlog > ~/man/git-shortlog.man; fi; \
if [ -n "$(man git-show;)" ]; then man git-show > ~/man/git-show.man; fi; \
if [ -n "$(man git-stash;)" ]; then man git-stash > ~/man/git-stash.man; fi; \
if [ -n "$(man git-status;)" ]; then man git-status > ~/man/git-status.man; fi; \
if [ -n "$(man git-submodule;)" ]; then man git-submodule > ~/man/git-submodule.man; fi; \
if [ -n "$(man git-tag;)" ]; then man git-tag > ~/man/git-tag.man; fi; \
if [ -n "$(man git-worktree;)" ]; then man git-worktree > ~/man/git-worktree.man; fi; \
if [ -n "$(man gitk;)" ]; then man gitk > ~/man/gitk.man; fi; \
if [ -n "$(man git-config;)" ]; then man git-config > ~/man/git-config.man; fi; \
if [ -n "$(man git-fast-export;)" ]; then man git-fast-export > ~/man/git-fast-export.man; fi; \
if [ -n "$(man git-fast-import;)" ]; then man git-fast-import > ~/man/git-fast-import.man; fi; \
if [ -n "$(man git-filter-branch;)" ]; then man git-filter-branch > ~/man/git-filter-branch.man; fi; \
if [ -n "$(man git-mergetool;)" ]; then man git-mergetool > ~/man/git-mergetool.man; fi; \
if [ -n "$(man git-pack-refs;)" ]; then man git-pack-refs > ~/man/git-pack-refs.man; fi; \
if [ -n "$(man git-prune;)" ]; then man git-prune > ~/man/git-prune.man; fi; \
if [ -n "$(man git-reflog;)" ]; then man git-reflog > ~/man/git-reflog.man; fi; \
if [ -n "$(man git-remote;)" ]; then man git-remote > ~/man/git-remote.man; fi; \
if [ -n "$(man git-repack;)" ]; then man git-repack > ~/man/git-repack.man; fi; \
if [ -n "$(man git-replace;)" ]; then man git-replace > ~/man/git-replace.man; fi; \
if [ -n "$(man git-annotate;)" ]; then man git-annotate > ~/man/git-annotate.man; fi; \
if [ -n "$(man git-blame;)" ]; then man git-blame > ~/man/git-blame.man; fi; \
if [ -n "$(man git-cherry;)" ]; then man git-cherry > ~/man/git-cherry.man; fi; \
if [ -n "$(man git-count-objects;)" ]; then man git-count-objects > ~/man/git-count-objects.man; fi; \
if [ -n "$(man git-difftool;)" ]; then man git-difftool > ~/man/git-difftool.man; fi; \
if [ -n "$(man git-fsck;)" ]; then man git-fsck > ~/man/git-fsck.man; fi; \
if [ -n "$(man git-get-tar-commit-id;)" ]; then man git-get-tar-commit-id > ~/man/git-get-tar-commit-id.man; fi; \
if [ -n "$(man git-help;)" ]; then man git-help > ~/man/git-help.man; fi; \
if [ -n "$(man git-instaweb;)" ]; then man git-instaweb > ~/man/git-instaweb.man; fi; \
if [ -n "$(man git-merge-tree;)" ]; then man git-merge-tree > ~/man/git-merge-tree.man; fi; \
if [ -n "$(man git-rerere;)" ]; then man git-rerere > ~/man/git-rerere.man; fi; \
if [ -n "$(man git-rev-parse;)" ]; then man git-rev-parse > ~/man/git-rev-parse.man; fi; \
if [ -n "$(man git-show-branch;)" ]; then man git-show-branch > ~/man/git-show-branch.man; fi; \
if [ -n "$(man git-verify-commit;)" ]; then man git-verify-commit > ~/man/git-verify-commit.man; fi; \
if [ -n "$(man git-verify-tag;)" ]; then man git-verify-tag > ~/man/git-verify-tag.man; fi; \
if [ -n "$(man git-whatchanged;)" ]; then man git-whatchanged > ~/man/git-whatchanged.man; fi; \
if [ -n "$(man gitweb;)" ]; then man gitweb > ~/man/gitweb.man; fi; \
if [ -n "$(man git-archimport;)" ]; then man git-archimport > ~/man/git-archimport.man; fi; \
if [ -n "$(man git-cvsexportcommit;)" ]; then man git-cvsexportcommit > ~/man/git-cvsexportcommit.man; fi; \
if [ -n "$(man git-cvsimport;)" ]; then man git-cvsimport > ~/man/git-cvsimport.man; fi; \
if [ -n "$(man git-cvsserver;)" ]; then man git-cvsserver > ~/man/git-cvsserver.man; fi; \
if [ -n "$(man git-imap-send;)" ]; then man git-imap-send > ~/man/git-imap-send.man; fi; \
if [ -n "$(man git-p4;)" ]; then man git-p4 > ~/man/git-p4.man; fi; \
if [ -n "$(man git-quiltimport;)" ]; then man git-quiltimport > ~/man/git-quiltimport.man; fi; \
if [ -n "$(man git-request-pull;)" ]; then man git-request-pull > ~/man/git-request-pull.man; fi; \
if [ -n "$(man git-send-email;)" ]; then man git-send-email > ~/man/git-send-email.man; fi; \
if [ -n "$(man git-svn;)" ]; then man git-svn > ~/man/git-svn.man; fi; \
if [ -n "$(man git-apply;)" ]; then man git-apply > ~/man/git-apply.man; fi; \
if [ -n "$(man git-checkout-index;)" ]; then man git-checkout-index > ~/man/git-checkout-index.man; fi; \
if [ -n "$(man git-commit-tree;)" ]; then man git-commit-tree > ~/man/git-commit-tree.man; fi; \
if [ -n "$(man git-hash-object;)" ]; then man git-hash-object > ~/man/git-hash-object.man; fi; \
if [ -n "$(man git-index-pack;)" ]; then man git-index-pack > ~/man/git-index-pack.man; fi; \
if [ -n "$(man git-merge-file;)" ]; then man git-merge-file > ~/man/git-merge-file.man; fi; \
if [ -n "$(man git-merge-index;)" ]; then man git-merge-index > ~/man/git-merge-index.man; fi; \
if [ -n "$(man git-mktag;)" ]; then man git-mktag > ~/man/git-mktag.man; fi; \
if [ -n "$(man git-mktree;)" ]; then man git-mktree > ~/man/git-mktree.man; fi; \
if [ -n "$(man git-pack-objects;)" ]; then man git-pack-objects > ~/man/git-pack-objects.man; fi; \
if [ -n "$(man git-prune-packed;)" ]; then man git-prune-packed > ~/man/git-prune-packed.man; fi; \
if [ -n "$(man git-read-tree;)" ]; then man git-read-tree > ~/man/git-read-tree.man; fi; \
if [ -n "$(man git-symbolic-ref;)" ]; then man git-symbolic-ref > ~/man/git-symbolic-ref.man; fi; \
if [ -n "$(man git-unpack-objects;)" ]; then man git-unpack-objects > ~/man/git-unpack-objects.man; fi; \
if [ -n "$(man git-update-index;)" ]; then man git-update-index > ~/man/git-update-index.man; fi; \
if [ -n "$(man git-update-ref;)" ]; then man git-update-ref > ~/man/git-update-ref.man; fi; \
if [ -n "$(man git-write-tree;)" ]; then man git-write-tree > ~/man/git-write-tree.man; fi; \
if [ -n "$(man git-cat-file;)" ]; then man git-cat-file > ~/man/git-cat-file.man; fi; \
if [ -n "$(man git-diff-files;)" ]; then man git-diff-files > ~/man/git-diff-files.man; fi; \
if [ -n "$(man git-diff-index;)" ]; then man git-diff-index > ~/man/git-diff-index.man; fi; \
if [ -n "$(man git-diff-tree;)" ]; then man git-diff-tree > ~/man/git-diff-tree.man; fi; \
if [ -n "$(man git-for-each-ref;)" ]; then man git-for-each-ref > ~/man/git-for-each-ref.man; fi; \
if [ -n "$(man git-ls-files;)" ]; then man git-ls-files > ~/man/git-ls-files.man; fi; \
if [ -n "$(man git-ls-remote;)" ]; then man git-ls-remote > ~/man/git-ls-remote.man; fi; \
if [ -n "$(man git-ls-tree;)" ]; then man git-ls-tree > ~/man/git-ls-tree.man; fi; \
if [ -n "$(man git-merge-base;)" ]; then man git-merge-base > ~/man/git-merge-base.man; fi; \
if [ -n "$(man git-name-rev;)" ]; then man git-name-rev > ~/man/git-name-rev.man; fi; \
if [ -n "$(man git-pack-redundant;)" ]; then man git-pack-redundant > ~/man/git-pack-redundant.man; fi; \
if [ -n "$(man git-rev-list;)" ]; then man git-rev-list > ~/man/git-rev-list.man; fi; \
if [ -n "$(man git-show-index;)" ]; then man git-show-index > ~/man/git-show-index.man; fi; \
if [ -n "$(man git-show-ref;)" ]; then man git-show-ref > ~/man/git-show-ref.man; fi; \
if [ -n "$(man git-unpack-file;)" ]; then man git-unpack-file > ~/man/git-unpack-file.man; fi; \
if [ -n "$(man git-var;)" ]; then man git-var > ~/man/git-var.man; fi; \
if [ -n "$(man git-verify-pack;)" ]; then man git-verify-pack > ~/man/git-verify-pack.man; fi; \
if [ -n "$(man git-daemon;)" ]; then man git-daemon > ~/man/git-daemon.man; fi; \
if [ -n "$(man git-fetch-pack;)" ]; then man git-fetch-pack > ~/man/git-fetch-pack.man; fi; \
if [ -n "$(man git-http-backend;)" ]; then man git-http-backend > ~/man/git-http-backend.man; fi; \
if [ -n "$(man git-send-pack;)" ]; then man git-send-pack > ~/man/git-send-pack.man; fi; \
if [ -n "$(man git-update-server-info;)" ]; then man git-update-server-info > ~/man/git-update-server-info.man; fi; \
if [ -n "$(man git-http-fetch;)" ]; then man git-http-fetch > ~/man/git-http-fetch.man; fi; \
if [ -n "$(man git-http-push;)" ]; then man git-http-push > ~/man/git-http-push.man; fi; \
if [ -n "$(man git-parse-remote;)" ]; then man git-parse-remote > ~/man/git-parse-remote.man; fi; \
if [ -n "$(man git-receive-pack;)" ]; then man git-receive-pack > ~/man/git-receive-pack.man; fi; \
if [ -n "$(man git-shell;)" ]; then man git-shell > ~/man/git-shell.man; fi; \
if [ -n "$(man git-upload-archive;)" ]; then man git-upload-archive > ~/man/git-upload-archive.man; fi; \
if [ -n "$(man git-upload-pack;)" ]; then man git-upload-pack > ~/man/git-upload-pack.man; fi; \
if [ -n "$(man git-check-attr;)" ]; then man git-check-attr > ~/man/git-check-attr.man; fi; \
if [ -n "$(man git-check-ignore;)" ]; then man git-check-ignore > ~/man/git-check-ignore.man; fi; \
if [ -n "$(man git-check-mailmap;)" ]; then man git-check-mailmap > ~/man/git-check-mailmap.man; fi; \
if [ -n "$(man git-check-ref-format;)" ]; then man git-check-ref-format > ~/man/git-check-ref-format.man; fi; \
if [ -n "$(man git-column;)" ]; then man git-column > ~/man/git-column.man; fi; \
if [ -n "$(man git-credential;)" ]; then man git-credential > ~/man/git-credential.man; fi; \
if [ -n "$(man git-credential-cache;)" ]; then man git-credential-cache > ~/man/git-credential-cache.man; fi; \
if [ -n "$(man git-credential-store;)" ]; then man git-credential-store > ~/man/git-credential-store.man; fi; \
if [ -n "$(man git-fmt-merge-msg;)" ]; then man git-fmt-merge-msg > ~/man/git-fmt-merge-msg.man; fi; \
if [ -n "$(man git-interpret-trailers;)" ]; then man git-interpret-trailers > ~/man/git-interpret-trailers.man; fi; \
if [ -n "$(man git-mailinfo;)" ]; then man git-mailinfo > ~/man/git-mailinfo.man; fi; \
if [ -n "$(man git-mailsplit;)" ]; then man git-mailsplit > ~/man/git-mailsplit.man; fi; \
if [ -n "$(man git-merge-one-file;)" ]; then man git-merge-one-file > ~/man/git-merge-one-file.man; fi; \
if [ -n "$(man git-patch-id;)" ]; then man git-patch-id > ~/man/git-patch-id.man; fi; \
if [ -n "$(man git-sh-i18n;)" ]; then man git-sh-i18n > ~/man/git-sh-i18n.man; fi; \
if [ -n "$(man git-sh-setup;)" ]; then man git-sh-setup > ~/man/git-sh-setup.man; fi; \
if [ -n "$(man git-stripspace;)" ]; then man git-stripspace > ~/man/git-stripspace.man; fi;