#!/bin/bash

TOTAL_MEMORY_IN_BYTES=$(free | grep 'Mem:' | awk '{print $2}'); \
THREE_QUARTERS_TOTAL_MEMORY_IN_BYTES=$(echo "${TOTAL_MEMORY_IN_BYTES} * 3 / 4" | bc); \
HALF_OF_TOTAL_MEMORY_IN_BYTES=$(echo "${TOTAL_MEMORY_IN_BYTES} / 2" | bc); \
ONE_QUARTER_OF_TOTAL_MEMORY_IN_BYTES=$(echo "${TOTAL_MEMORY_IN_BYTES} / 4" | bc);

echo "TOTAL_MEMORY_IN_BYTES = [ ${TOTAL_MEMORY_IN_BYTES} ]"; \
echo "THREE_QUARTERS_TOTAL_MEMORY_IN_BYTES = [ ${THREE_QUARTERS_TOTAL_MEMORY_IN_BYTES} ]"; \
echo "HALF_OF_TOTAL_MEMORY_IN_BYTES = [ ${HALF_OF_TOTAL_MEMORY_IN_BYTES} ]"; \
echo "ONE_QUARTER_OF_TOTAL_MEMORY_IN_BYTES = [ ${ONE_QUARTER_OF_TOTAL_MEMORY_IN_BYTES} ]";



# cat /proc/meminfo
